# Fly.io config for Darwin Broker
app = "railhopp-darwin-broker"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "4001"

[[services]]
  protocol = "tcp"
  internal_port = 4001

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

  [[services.http_checks]]
    interval = "15s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "2s"

  [services.autoscaling]
    min_machines = 1
    max_machines = 3