# fly.toml app configuration file generated for railhopp-websocket
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "railhopp-websocket"
primary_region = "lhr"  # London - closest to UK users and Network Rail data

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  
  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
